spring:
  application:
    name: db-transaction

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://node-101:3306/seckill
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 10


  redis:
    cluster:
     nodes: node-101:6379,node-101:6380,node-102:6379,node-102:6380,node-103:6379,node-103:6380
#      nodes: redis://node-101:6379,redis://node-101:6380,redis://node-102:6379,redis://node-102:6380,redis://node-103:6379,redis://node-103:6380

mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
